version: "3.9"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
